import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Index.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Multi-Dex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Choose Pokedex</h1>
      <div className={styles.pokedexOpts}>
        <Link href='/kalos' className={styles.pokedexOpt}>
          <picture>
            <img className={styles.pokedexImg} src='/img/kalos.webp' alt='Kalos Pokedex'></img>
          </picture>
          <div>Kalos Pokedex</div></Link>
      </div>
    </div>
  )
}
